### ISSUE TITLE
can't install Slack-app

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.slack#2]
I get to fill in the team and login/pass but then the popup says I'm not authorized to install Homey:
![2017-07-03 17_37_31- 243 settings - homey](https://user-images.githubusercontent.com/1064079/27800335-37afb790-6019-11e7-9d33-d4ef0fcdb323.png)

**Comment by WeeJeWel** [comment]
This is not a bug but a policy on the Slack channel.

**Comment by bvdbos** [comment]
Then we'd better delete the app from the store? 
![2017-07-03 18_36_58- 243 flow - homey](https://user-images.githubusercontent.com/1064079/27801496-a6bae06a-601e-11e7-8455-bde713768016.png)

**Comment by WeeJeWel** [comment]
No, the app is still useful for teams where 3rd party integrations are
enabled.
