### ISSUE TITLE
Solution for Slack notifications for images

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.slack#5]
Images posted on Slack using the new image token dont trigger a Slack notification (while posted messages do). My guess is that this is due to the fact that image are posted to the channel under your own username while message are posted as Slackbot.

It would be great to have Slack notifications when images are posted.

**Comment by WeeJeWel** [comment]
This is a Slack API limitation I'm afraid. Add another card to trigger a message as well :)

**Comment by jghaanstra** [comment]
Ok thanx.

Just for reference, the work around is to create another Slack user (for instance with username Homey) specifically for Homey and make that user Owner of the workspace your are posting too as well.
