### ISSUE TITLE
Images Are Sent As User Not App

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.slack#7]
When sending text messages via Slack, they are sent by “Homey (App)”.  For example:
![4e117403-c850-4c9e-b7f5-326534be49fc](https://user-images.githubusercontent.com/10297361/35831847-70c4b2ee-0acb-11e8-896e-3d990218a6be.jpeg)

However, when you send an image (for example one grabbed by ImageGrabber), the image is sent as the user who connected the app to Slack instead of being sent by “Homey (App)” as is when sending text. 

Expectation is that the image should also be sent by Homey (App).

**Comment by WeeJeWel** [comment]
See https://github.com/athombv/com.slack/issues/5, this is a Slack API limitation.
